// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeightMaster.Config;

#nullable disable

namespace WeightMaster.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250321115526_final")]
    partial class final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WeightMaster.Models.FinalTransactionBlockModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("ActualNormalLeafWeight")
                        .HasColumnType("float");

                    b.Property<int>("BagCount")
                        .HasColumnType("int");

                    b.Property<float>("BagWeight")
                        .HasColumnType("float");

                    b.Property<string>("BarcodeDetails")
                        .HasColumnType("longtext");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FinalGoldLeafCount")
                        .HasColumnType("int");

                    b.Property<int>("FinalGreenLeafCount")
                        .HasColumnType("int");

                    b.Property<string>("LeafWeightOfficer")
                        .HasColumnType("longtext");

                    b.Property<string>("LineName")
                        .HasColumnType("longtext");

                    b.Property<float>("MaximumNormalLeafWeight")
                        .HasColumnType("float");

                    b.Property<float>("Morapuwata")
                        .HasColumnType("float");

                    b.Property<string>("NameWithInitials")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<float>("RealValue")
                        .HasColumnType("float");

                    b.Property<float>("Reject")
                        .HasColumnType("float");

                    b.Property<string>("Supervisor")
                        .HasColumnType("longtext");

                    b.Property<float>("Thambimata")
                        .HasColumnType("float");

                    b.Property<float>("TotalGoldLeafWeight")
                        .HasColumnType("float");

                    b.Property<float>("TotalLeafWeight")
                        .HasColumnType("float");

                    b.Property<string>("TransportAgent")
                        .HasColumnType("longtext");

                    b.Property<float>("Water")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FinaltransactionData");
                });

            modelBuilder.Entity("WeightMaster.Models.LineMasterBlockModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("LineMaster")
                        .HasColumnType("longtext");

                    b.Property<string>("LineName")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("lineMasterData");
                });

            modelBuilder.Entity("WeightMaster.Models.MemberBlockModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CellNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomMemberNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomNameWithInitials")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MembersData");
                });

            modelBuilder.Entity("WeightMaster.Models.RunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FinalTransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FinalTransactionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("RunLog");
                });

            modelBuilder.Entity("WeightMaster.Models.TransactionLogBlockModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("ActualNormalLeafWeight")
                        .HasColumnType("float");

                    b.Property<int>("BagCount")
                        .HasColumnType("int");

                    b.Property<string>("BarcodeDetails")
                        .HasColumnType("longtext");

                    b.Property<int>("BoxCount")
                        .HasColumnType("int");

                    b.Property<float>("BoxWeight")
                        .HasColumnType("float");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FinalGoldLeafCount")
                        .HasColumnType("int");

                    b.Property<int>("FinalGreenLeafCount")
                        .HasColumnType("int");

                    b.Property<string>("LeafWeightOfficer")
                        .HasColumnType("longtext");

                    b.Property<string>("LineName")
                        .HasColumnType("longtext");

                    b.Property<float>("MaximumNormalLeafWeight")
                        .HasColumnType("float");

                    b.Property<float>("Morapuwata")
                        .HasColumnType("float");

                    b.Property<string>("NameWithInitials")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<float>("RealValue")
                        .HasColumnType("float");

                    b.Property<float>("Reject")
                        .HasColumnType("float");

                    b.Property<string>("Supervisor")
                        .HasColumnType("longtext");

                    b.Property<float>("Thambimata")
                        .HasColumnType("float");

                    b.Property<float>("TotalGoldLeafWeight")
                        .HasColumnType("float");

                    b.Property<float>("TotalLeafWeight")
                        .HasColumnType("float");

                    b.Property<string>("TransportAgent")
                        .HasColumnType("longtext");

                    b.Property<float>("Water")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("transactionData");
                });

            modelBuilder.Entity("WeightMaster.Models.UserBlockModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasColumnType("longtext");

                    b.Property<string>("ApiSecret")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UsersData");
                });

            modelBuilder.Entity("WeightMaster.Models.UserLoginModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LoginDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("UserLoginsLog");
                });

            modelBuilder.Entity("WeightMaster.Models.RunLog", b =>
                {
                    b.HasOne("WeightMaster.Models.FinalTransactionBlockModel", "FinalTransaction")
                        .WithMany()
                        .HasForeignKey("FinalTransactionId");

                    b.HasOne("WeightMaster.Models.TransactionLogBlockModel", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId");

                    b.Navigation("FinalTransaction");

                    b.Navigation("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
