// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeightMaster.Config;

#nullable disable

namespace WeightMaster.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250615060902_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WeightMaster.Models.FinalTransactionBlockModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("actual_nomal_leaf_weight")
                        .HasColumnType("int");

                    b.Property<int>("bag_count")
                        .HasColumnType("int");

                    b.Property<int>("bag_weight")
                        .HasColumnType("int");

                    b.Property<string>("barcode_details")
                        .HasColumnType("longtext");

                    b.Property<string>("company")
                        .HasColumnType("longtext");

                    b.Property<string>("date")
                        .HasColumnType("longtext");

                    b.Property<int>("final_gold_leaf_count")
                        .HasColumnType("int");

                    b.Property<int>("final_green_leaf_count")
                        .HasColumnType("int");

                    b.Property<string>("leaf_weight_officer")
                        .HasColumnType("longtext");

                    b.Property<string>("linename")
                        .HasColumnType("longtext");

                    b.Property<int>("maximum_nomal_leaf_weight")
                        .HasColumnType("int");

                    b.Property<int>("morapuwata")
                        .HasColumnType("int");

                    b.Property<string>("name_with_initials")
                        .HasColumnType("longtext");

                    b.Property<string>("phone_number")
                        .HasColumnType("longtext");

                    b.Property<float>("real_value")
                        .HasColumnType("float");

                    b.Property<int>("reject")
                        .HasColumnType("int");

                    b.Property<string>("superviosr")
                        .HasColumnType("longtext");

                    b.Property<int>("thambimata")
                        .HasColumnType("int");

                    b.Property<int>("total_gold_leaf_weight")
                        .HasColumnType("int");

                    b.Property<int>("total_leaf_weight")
                        .HasColumnType("int");

                    b.Property<string>("transportagent")
                        .HasColumnType("longtext");

                    b.Property<int>("water")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FinaltransactionData");
                });

            modelBuilder.Entity("WeightMaster.Models.GreenLeafPostModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("bag_count")
                        .HasColumnType("int");

                    b.Property<double>("bag_weight")
                        .HasColumnType("double");

                    b.Property<int>("box_count")
                        .HasColumnType("int");

                    b.Property<double>("box_weight")
                        .HasColumnType("double");

                    b.Property<string>("created_user")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("factory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("final_gold_leaf_count")
                        .HasColumnType("int");

                    b.Property<int>("final_green_leaf_count")
                        .HasColumnType("int");

                    b.Property<double>("gold_leaf_weight")
                        .HasColumnType("double");

                    b.Property<string>("leaf_handover_date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("leaf_weight_officer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("membernumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("morapuwata")
                        .HasColumnType("double");

                    b.Property<double>("nomal_leaf_weight")
                        .HasColumnType("double");

                    b.Property<string>("premembernumber")
                        .HasColumnType("longtext");

                    b.Property<double>("real_weight")
                        .HasColumnType("double");

                    b.Property<double>("rejected")
                        .HasColumnType("double");

                    b.Property<string>("supervisor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("thambimata")
                        .HasColumnType("double");

                    b.Property<double>("total_weight")
                        .HasColumnType("double");

                    b.Property<string>("transportagent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("transportlinename")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("updated_user")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("wathurata")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("GreenLeafPosts");
                });

            modelBuilder.Entity("WeightMaster.Models.LineBlockModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LineMaster")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("lineDbLog");
                });

            modelBuilder.Entity("WeightMaster.Models.LineMasterBlockModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("LineMaster")
                        .HasColumnType("longtext");

                    b.Property<string>("LineName")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("lineMasterData");
                });

            modelBuilder.Entity("WeightMaster.Models.MemberBlockModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CellNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomMemberNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomNameWithInitials")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MembersData");
                });

            modelBuilder.Entity("WeightMaster.Models.PostStatusModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("PostStatus");
                });

            modelBuilder.Entity("WeightMaster.Models.RunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FinalTransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FinalTransactionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("RunLog");
                });

            modelBuilder.Entity("WeightMaster.Models.TransactionLogBlockModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("actual_nomal_leaf_weight")
                        .HasColumnType("int");

                    b.Property<int>("bag_count")
                        .HasColumnType("int");

                    b.Property<string>("barcode_details")
                        .HasColumnType("longtext");

                    b.Property<int>("box_count")
                        .HasColumnType("int");

                    b.Property<int>("box_weight")
                        .HasColumnType("int");

                    b.Property<string>("company")
                        .HasColumnType("longtext");

                    b.Property<string>("date")
                        .HasColumnType("longtext");

                    b.Property<int>("final_gold_leaf_count")
                        .HasColumnType("int");

                    b.Property<int>("final_green_leaf_count")
                        .HasColumnType("int");

                    b.Property<string>("leaf_weight_officer")
                        .HasColumnType("longtext");

                    b.Property<string>("linename")
                        .HasColumnType("longtext");

                    b.Property<int>("maximum_nomal_leaf_weight")
                        .HasColumnType("int");

                    b.Property<int>("morapuwata")
                        .HasColumnType("int");

                    b.Property<string>("name_with_initials")
                        .HasColumnType("longtext");

                    b.Property<string>("phone_number")
                        .HasColumnType("longtext");

                    b.Property<double>("real_value")
                        .HasColumnType("double");

                    b.Property<int>("reject")
                        .HasColumnType("int");

                    b.Property<string>("superviosr")
                        .HasColumnType("longtext");

                    b.Property<int>("thambimata")
                        .HasColumnType("int");

                    b.Property<int>("total_gold_leaf_weight")
                        .HasColumnType("int");

                    b.Property<int>("total_leaf_weight")
                        .HasColumnType("int");

                    b.Property<string>("transportagent")
                        .HasColumnType("longtext");

                    b.Property<int>("water")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("transactionData");
                });

            modelBuilder.Entity("WeightMaster.Models.UserBlockModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasColumnType("longtext");

                    b.Property<string>("ApiSecret")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UsersData");
                });

            modelBuilder.Entity("WeightMaster.Models.UserLoginModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LoginDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("UserLoginsLog");
                });

            modelBuilder.Entity("WeightMaster.Models.memDbLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CellNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomMemberNum")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomNameWithInitials")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomPreMemberNum")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("memDbLog");
                });

            modelBuilder.Entity("WeightMaster.Models.RunLog", b =>
                {
                    b.HasOne("WeightMaster.Models.FinalTransactionBlockModel", "FinalTransaction")
                        .WithMany()
                        .HasForeignKey("FinalTransactionId");

                    b.HasOne("WeightMaster.Models.TransactionLogBlockModel", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId");

                    b.Navigation("FinalTransaction");

                    b.Navigation("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
